In [234]:
import csv
csv_file=open('CoolingLoad_Total18months.csv')
csv_reader_lines = csv.reader(csv_file)
a=[]
number = 0
for one_line in csv_reader_lines:
    a.append(one_line)
    number = number + 1

In [319]:
from datetime import datetime
import numpy as np
everyday_a=[]
total_a=[]
before = datetime.strptime(a[1][0],'%Y/%m/%d %H:%M').strftime('%Y-%m-%d')
number = 0
for item in a[1:len(a)]:
    now = datetime.strptime(item[0],'%Y/%m/%d %H:%M').strftime('%Y-%m-%d')
    if now == before:
        flag=1
        for obj in item:
            if obj == '':
                flag = 0
                break
        if flag ==1:
            everyday_a.append(item)
            number = number + 1
    else:
        if number < 96:
            everyday_a=[]
        else:
            total_a.append(everyday_a)
            everyday_a=[]
        before = now
        flag=1
        for obj in item:
            if obj == '':
                flag = 0
                break
        if flag ==1:
            everyday_a.append(item)
            number = 1
        else: number = 0

total_a = np.array(total_a)
# print(total_a.shape)
input_array = total_a[:,:,0:5]
insert_array = np.array([0])
new_input_array = []
for item in input_array:
    new_item = np.insert(item,5,values=insert_array,axis=1)
    new_input_array.append(new_item)
for item in new_input_array:
    for each in item:
        hours = datetime.strptime(str(each[0]),'%Y/%m/%d %H:%M').strftime('%H')
        if 17 > int(hours) > 9:
            each[5] = 1
new_input_array = np.array(new_input_array)
np.save("input_18month_no_nan.npy",new_input_array[:,:,1:6])
# loaddata = np.load("input_18month_no_nan.npy")
# print(loaddata.shape)
# print(loaddata)

output_array = total_a[:,:,7]
output_save = []
item_save = []
for item in output_array:
    new = float(item[0])
    i = 0
    for j in range(1,len(item)):
        if i < 3:
            new = new + float(item[j])
            i =i + 1
        else:
            new = new/4
            item_save.append(new)
            i = 0
            new = float(item[j])
    item_save.append(new/4)
    output_save.append(item_save)
    item_save = []

output_save = np.array(output_save)
np.save("output_18month_no_nan.npy",output_save)
# loaddata = np.load("output_18month_no_nan.npy")
# print(loaddata.shape)
# print(loaddata)









(166, 24)
[[1147.327831   1270.56310075 1364.17355325 ... 1537.5019415
  1507.60595325 1263.83254825]
 [1040.146176   1076.77002425 1206.62872975 ... 1314.9919105
  1263.10446925 1026.41066548]
 [1186.05820875 1215.757379   1227.54629275 ... 1351.92002575
  1386.50540075 1178.6067273 ]
 ...
 [ 999.6298946   971.62949125  810.01231173 ... 1264.74225125
  1106.78499425  672.76561625]
 [ 821.308002    839.6150309   980.47524655 ... 1062.24283633
   962.18520075  904.46287995]
 [1014.8392135   992.10462825 1094.65785125 ... 1186.6569175
  1186.8166205   822.70818033]]


In [197]:
import pandas as pd

a=pd.read_csv('./CoolingLoad_Total18months.csv',parse_dates=['Timestamp'])
a = a.dropna(axis=0,how='any')
print(a)
print(type(a))

                Timestamp  Average_OAT   Humidity  UV_Index  Average_Rainfall  \
1368  2020-04-15 06:00:00    19.652167  65.941000       0.3               0.0   
1369  2020-04-15 06:15:00    19.543867  65.414333       0.3               0.0   
1370  2020-04-15 06:30:00    19.843017  64.734333       0.3               0.0   
1371  2020-04-15 06:45:00    20.200450  64.029333       0.3               0.0   
1372  2020-04-15 07:00:00    20.659600  62.986000       0.3               0.0   
...                   ...          ...        ...       ...               ...   
52603 2021-09-30 22:45:00    29.455333  89.167967       0.1               0.0   
52604 2021-09-30 23:00:00    29.436167  89.717967       0.1               0.0   
52605 2021-09-30 23:15:00    29.387000  90.504633       0.1               0.0   
52606 2021-09-30 23:30:00    29.354500  89.817967       0.1               0.0   
52607 2021-09-30 23:45:00    24.186667  75.112750       0.1               0.0   

       NT_CoolingLoad  ST_C

In [219]:
import numpy as np
loaddata = np.load("inputn.npy")
print(loaddata.shape)
print(loaddata)

(8298, 5, 4)
[[[ 19.65216667  19.54386667  19.84301667  20.20045   ]
  [ 65.941       65.41433333  64.73433333  64.02933333]
  [  0.3          0.3          0.3          0.3       ]
  [  0.           0.           0.           0.        ]
  [  6.           2.         106.           0.        ]]

 [[ 20.6596      21.66126667  22.10293333  22.0396    ]
  [ 62.986       59.19756667  59.6259      61.4693    ]
  [  0.3          0.3          0.3          0.3       ]
  [  0.           0.           0.           0.        ]
  [  7.           2.         106.           0.        ]]

 [[ 22.07293333  22.29876667  22.63293333  22.83043333]
  [ 60.47593333  59.56756667  56.09756667  56.3809    ]
  [  0.3          0.5          0.5          0.5       ]
  [  0.           0.           0.           0.        ]
  [  8.           2.         106.           0.        ]]

 ...

 [[ 29.582       29.4845      29.49533333  29.41283333]
  [ 82.1212      82.56123333  82.78786667  85.33793333]
  [  0.4          0.4  